Task - 1 There are three different tables as given above. Please make three dataframe in python
and save them as three .csv files. From Task 2 to Task 10, use the saved .csv files only.

In [13]:
#Before starting the project we need to import pandas and numpy libraries.
import pandas as pd
import numpy as np

In [31]:
# creating the first dataframe table that is project data frame
project_data = pd.DataFrame(
    [
    ["A001","project 1",1002000,"Finished"],
    ["A002","project 2",2000000,"Ongoing"],
    ["A003","project 3",4500000,"Finished"],
    ["A004","project 4",5500000,"Ongoing"],
    ["A005","project 5",np.nan,"Finished"],
    ["A002","project 6",680000,"Failed"],
    ["A005", "project 7",400000,"Finished"],
    ["A003","project 8",350000,"Failed"],
    ["A001","project 9",np.nan,"Ongoing"],
    ["A003","project 10",300000,"Finished"],
    ["A001","project 11",2000000,"Failed"],
    ["A004","project 12",1000000,"Ongoing"],
    ["A004","project 13",3000000,"Finished"],
    ["A005","project 14",200000,"Finished"]],
    columns = ["ID","Project","Cost","Status"]
                                  )
project_data

      ID     Project       Cost    Status
0   A001   project 1  1002000.0  Finished
1   A002   project 2  2000000.0   Ongoing
2   A003   project 3  4500000.0  Finished
3   A004   project 4  5500000.0   Ongoing
4   A005   project 5        NaN  Finished
5   A002   project 6   680000.0    Failed
6   A005   project 7   400000.0  Finished
7   A003   project 8   350000.0    Failed
8   A001   project 9        NaN   Ongoing
9   A003  project 10   300000.0  Finished
10  A001  project 11  2000000.0    Failed
11  A004  project 12  1000000.0   Ongoing
12  A004  project 13  3000000.0  Finished
13  A005  project 14   200000.0  Finished

In [32]:
# now im saving the first dataframe as csv format
project_data.to_csv("project_data.csv",index = False)

In [33]:
# I have created the second data frame called the employee_data

Employee_data = pd.DataFrame(
    [
        ["A001","John Alter","M","Paris",25],
        ["A002","Alice Luxumberg","F","London",27],
        ["A003","Tom Sabestine","M","Berlin",29],
        ["A004","Nina Adgra","F","Newyork",31],
        ["A005","Amy Johny","F","Madrid",30]]
    ,columns = ["ID","Name","Gender","City","Age"])
Employee_data

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [34]:
#Now im  saving this data as csv 
Employee_data.to_csv("Employee_data.csv", index = False)

In [35]:
#now im creating the last data frame that is Seniority level dataframe

Seniority_level = pd.DataFrame([
    ["A001",2],
    ["A002",2],
    ["A003",3],
    ["A004",2],
    ["A005",3],
],columns = ["ID","Designation Level"])
Seniority_level

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [36]:
#Now im saving this data frame as well
Seniority_level.to_csv("Seniority_level.csv",index =False)

Task 2 - The cost column in the dataframe “Project” has some missing values. Your task is to
compute these missing values. Replace the missing values by running average. You
should use the “For” loop for this task.

In [37]:
# starting with sum = 0 and count = 0
# these will help us calculate the running average
cost_sum = 0
count = 0

# loop through each row of the dataframe
for i in range(len(project_data)):
    
    # check if the Cost value is missing
    if pd.isna(project_data.loc[i, "Cost"]):
        
        # calculate running average using previous values
        running_avg = cost_sum / count
        
        # replace the missing value with running average
        project_data.loc[i, "Cost"] = running_avg
        
        # add this value to the sum and increase count
        cost_sum += running_avg
        count += 1
        
    else:
        # if cost value already exists
        # add it to running sum
        cost_sum += project_data.loc[i, "Cost"]
        
        # increase the count
        count += 1


# remove extra column "cost" if it exists
if "cost" in project_data.columns:
    project_data = project_data.drop(columns=["Cost"])

# display the dataframe
project_data

      ID     Project       Cost    Status
0   A001   project 1  1002000.0  Finished
1   A002   project 2  2000000.0   Ongoing
2   A003   project 3  4500000.0  Finished
3   A004   project 4  5500000.0   Ongoing
4   A005   project 5  3250500.0  Finished
5   A002   project 6   680000.0    Failed
6   A005   project 7   400000.0  Finished
7   A003   project 8   350000.0    Failed
8   A001   project 9  2210312.5   Ongoing
9   A003  project 10   300000.0  Finished
10  A001  project 11  2000000.0    Failed
11  A004  project 12  1000000.0   Ongoing
12  A004  project 13  3000000.0  Finished
13  A005  project 14   200000.0  Finished

Task 3
Split the name column in the Employee dataframe into two new columns “First Name”,
and “LastName” and remove the older “name” column.

In [38]:
# split the Name column into two parts using space
# expand=True creates two separate columns
Employee_data[["First Name","LastName"]] = Employee_data["Name"].str.split(" ", expand=True)

# remove the old Name column since we already created first and last name
Employee_data = Employee_data.drop(columns=["Name"])

# display the dataframe
Employee_data

     ID Gender     City  Age First Name   LastName
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

Task 4
Join all three dataframes in one single dataframe. Name it “Final”

In [39]:
# first we need to merge the project data and employee data on the basis of id.
# this will combine project details with employee details
Final = pd.merge(project_data, Employee_data, on="ID")

# now we will merge the result with third table that is seniority level using id column.
# this will add designation level for each employee
Final = pd.merge(Final, Seniority_level, on="ID")

# display the final combined dataframe
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,LastName,Designation Level
0,A001,project 1,1002000.0,Finished,M,Paris,25,John,Alter,2
1,A002,project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3
5,A002,project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2
6,A005,project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3
7,A003,project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2
9,A003,project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,project 11,2000000.0,Failed,M,Paris,25,John,Alter,2
11,A004,project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3

Task 5
Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project
cost only to employees who have finished the projects.

In [40]:
# we need to create a bonus column and give value 0 
Final["Bonus"] = 0

# for loop is created to go through each row and identify the status is finished or not.
for i in range(len(Final)):
    
    # this loop checks if the status is finished.
    if Final.loc[i, "Status"] == "Finished":
        
        # at last we will multiply by 0.05 to get the final bonus amount.
        Final.loc[i, "Bonus"] = Final.loc[i, "Cost"] * 0.05

# display the final dataframe
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,LastName,Designation Level,Bonus
0,A001,project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100
1,A002,project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0
2,A003,project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000
3,A004,project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0
4,A005,project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525
5,A002,project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,2,0
6,A005,project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000
7,A003,project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,3,0
8,A001,project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0
9,A003,project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000
10,A001,project 11,2000000.0,Failed,M,Paris,25,John,Alter,2,0
11,A004,project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0
12,A004,project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000

Task 6
Demote the designation level by 1, whose projects have status “fail”. Delete the
employees record whose designation level is above 4.

In [41]:
# using for loop to check each row
for i in range(len(Final)):
    
    # checking if the status is failed or not.
    if Final.loc[i, "Status"] == "Failed":
        
        # time to reduce the designation level by 1 for failed projects
        Final.loc[i, "Designation Level"] = Final.loc[i, "Designation Level"] - 1


# removeing the employees whose designation level is more than 4
Final = Final[Final["Designation Level"] <= 4]

# display the updated dataframe
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,LastName,Designation Level,Bonus
0,A001,project 1,1002000.0,Finished,M,Paris,25,John,Alter,2,50100
1,A002,project 2,2000000.0,Ongoing,F,London,27,Alice,Luxumberg,2,0
2,A003,project 3,4500000.0,Finished,M,Berlin,29,Tom,Sabestine,3,225000
3,A004,project 4,5500000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0
4,A005,project 5,3250500.0,Finished,F,Madrid,30,Amy,Johny,3,162525
5,A002,project 6,680000.0,Failed,F,London,27,Alice,Luxumberg,1,0
6,A005,project 7,400000.0,Finished,F,Madrid,30,Amy,Johny,3,20000
7,A003,project 8,350000.0,Failed,M,Berlin,29,Tom,Sabestine,2,0
8,A001,project 9,2210312.5,Ongoing,M,Paris,25,John,Alter,2,0
9,A003,project 10,300000.0,Finished,M,Berlin,29,Tom,Sabestine,3,15000
10,A001,project 11,2000000.0,Failed,M,Paris,25,John,Alter,1,0
11,A004,project 12,1000000.0,Ongoing,F,Newyork,31,Nina,Adgra,2,0
12,A004,project 13,3000000.0,Finished,F,Newyork,31,Nina,Adgra,2,150000
13,A005,project 14,200000.0,Finished,F,Madrid,30,Amy,Johny,3,10000

Task 7
Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

In [42]:
# creating for loop to go through each row
for i in range(len(Final)):
    
    # checking if the gender is male
    if Final.loc[i, "Gender"] == "M":
        
        # if its male add mr
        Final.loc[i, "First Name"] = "Mr. " + Final.loc[i, "First Name"]
    
    else:
        # iif its female add mrs
        Final.loc[i, "First Name"] = "Mrs. " + Final.loc[i, "First Name"]


# at last we need to remove gender column becuase its not needed
Final = Final.drop(columns=["Gender"])

# display the dataframe
Final

,ID,Project,Cost,Status,City,Age,First Name,LastName,Designation Level,Bonus
0,A001,project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100
1,A002,project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
2,A003,project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000
3,A004,project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0
4,A005,project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,3,162525
5,A002,project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0
6,A005,project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,20000
7,A003,project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,2,0
8,A001,project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0
9,A003,project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000
10,A001,project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,1,0
11,A004,project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0
12,A004,project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000
13,A005,project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,3,10000

Task 8
Promote designation level by 1 for the employees whose age is more than 29 years using
IF condition.

In [45]:
# going through all row using for loop
for i in range(len(Final)):
    
    # checking if the age is more than 29
    if Final.loc[i, "Age"] > 29:
        
        # Add 1 for each designation level if age is more than 29
        Final.loc[i, "Designation Level"] = Final.loc[i, "Designation Level"] + 1


# display the updated dataframe
Final

,ID,Project,Cost,Status,City,Age,First Name,LastName,Designation Level,Bonus
0,A001,project 1,1002000.0,Finished,Paris,25,Mr. John,Alter,2,50100
1,A002,project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
2,A003,project 3,4500000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,225000
3,A004,project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
4,A005,project 5,3250500.0,Finished,Madrid,30,Mrs. Amy,Johny,4,162525
5,A002,project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0
6,A005,project 7,400000.0,Finished,Madrid,30,Mrs. Amy,Johny,4,20000
7,A003,project 8,350000.0,Failed,Berlin,29,Mr. Tom,Sabestine,2,0
8,A001,project 9,2210312.5,Ongoing,Paris,25,Mr. John,Alter,2,0
9,A003,project 10,300000.0,Finished,Berlin,29,Mr. Tom,Sabestine,3,15000
10,A001,project 11,2000000.0,Failed,Paris,25,Mr. John,Alter,1,0
11,A004,project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
12,A004,project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000
13,A005,project 14,200000.0,Finished,Madrid,30,Mrs. Amy,Johny,4,10000

Task 9
Add the cost of all projects for each Employee and save it in new dataframe
“TotalProjCost” with three columns ID, First Name, and Total cost

In [46]:
# using group by we can add the cost of each employee's project
# we need to rest index so that grouped column will not become index.
TotalProjCost = Final.groupby(["ID","First Name"])["Cost"].sum().reset_index()

# rename the Cost column to Total cost
TotalProjCost = TotalProjCost.rename(columns={"Cost":"Total cost"})

# display the new dataframe
TotalProjCost

     ID  First Name  Total cost
0  A001    Mr. John   5212312.5
1  A002  Mrs. Alice   2680000.0
2  A003     Mr. Tom   5150000.0
3  A004   Mrs. Nina   9500000.0
4  A005    Mrs. Amy   3850500.0

Task 10
Print all the employee details whose city name contains the letter “o” in it.

In [48]:
# selecting only the rows that contains 0
# str.contains checks if the letter exists in the city name
employees_with_o = Final[Final["City"].str.contains("o")]

# display the result
employees_with_o

,ID,Project,Cost,Status,City,Age,First Name,LastName,Designation Level,Bonus
1,A002,project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0
3,A004,project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
5,A002,project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0
11,A004,project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0
12,A004,project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000